-- MySQL Script generated by MySQL Workbench
-- Thu Jul  7 19:13:47 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cs340_russda
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cs340_russda
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cs340_russda` DEFAULT CHARACTER SET utf8 ;
USE `cs340_russda` ;

-- -----------------------------------------------------
-- Table `cs340_russda`.`Dungeon_Masters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs340_russda`.`Dungeon_Masters` (
  `dungeon_master_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lucky_dice` VARCHAR(45) NULL,
  PRIMARY KEY (`dungeon_master_id`),
  UNIQUE INDEX `dungeon_master_id_UNIQUE` (`dungeon_master_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs340_russda`.`Biomes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs340_russda`.`Biomes` (
  `biome_id` INT NOT NULL AUTO_INCREMENT,
  `biome_name` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`biome_id`),
  UNIQUE INDEX `biome_id_UNIQUE` (`biome_id` ASC) VISIBLE,
  UNIQUE INDEX `biome_UNIQUE` (`biome_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs340_russda`.`Dungeons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs340_russda`.`Dungeons` (
  `dungeon_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  `light_level` INT NOT NULL,
  `Biomes_biome_id` INT NOT NULL,
  PRIMARY KEY (`dungeon_id`),
  UNIQUE INDEX `dungeon_id_UNIQUE` (`dungeon_id` ASC) VISIBLE,
  INDEX `fk_Dungeons_Biomes1_idx` (`Biomes_biome_id` ASC) VISIBLE,
  CONSTRAINT `fk_Dungeons_Biomes1`
    FOREIGN KEY (`Biomes_biome_id`)
    REFERENCES `cs340_russda`.`Biomes` (`biome_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs340_russda`.`Scenarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs340_russda`.`Scenarios` (
  `scenario_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `summary` TEXT NULL,
  `target_level` INT NOT NULL,
  `session_time` DATE NULL,
  `Dungeon_Masters_dungeon_master_id` INT NOT NULL,
  `Dungeons_dungeon_id` INT NOT NULL,
  PRIMARY KEY (`scenario_id`),
  UNIQUE INDEX `scenario_id_UNIQUE` (`scenario_id` ASC) VISIBLE,
  INDEX `fk_Scenarios_Dungeon_Masters1_idx` (`Dungeon_Masters_dungeon_master_id` ASC) VISIBLE,
  INDEX `fk_Scenarios_Dungeons1_idx` (`Dungeons_dungeon_id` ASC) VISIBLE,
  CONSTRAINT `fk_Scenarios_Dungeon_Masters1`
    FOREIGN KEY (`Dungeon_Masters_dungeon_master_id`)
    REFERENCES `cs340_russda`.`Dungeon_Masters` (`dungeon_master_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Scenarios_Dungeons1`
    FOREIGN KEY (`Dungeons_dungeon_id`)
    REFERENCES `cs340_russda`.`Dungeons` (`dungeon_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs340_russda`.`Monsters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs340_russda`.`Monsters` (
  `monster_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  `challenge_rating` INT NOT NULL,
  `health_points` INT NOT NULL,
  `strength` INT NOT NULL,
  `dexterity` INT NOT NULL,
  `constitution` INT NOT NULL,
  `intelligence` INT NOT NULL,
  `wisdom` INT NOT NULL,
  `charisma` INT NOT NULL,
  `armor_class` INT NOT NULL,
  `talent` VARCHAR(256) NULL,
  PRIMARY KEY (`monster_id`),
  UNIQUE INDEX `monster_id_UNIQUE` (`monster_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs340_russda`.`Types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs340_russda`.`Types` (
  `type_id` INT NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`type_id`),
  UNIQUE INDEX `type_id_UNIQUE` (`type_id` ASC) VISIBLE,
  UNIQUE INDEX `type_UNIQUE` (`type_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs340_russda`.`Items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs340_russda`.`Items` (
  `item_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  `weight` DECIMAL(6,2) NOT NULL,
  `value` INT NOT NULL,
  `Types_type_id` INT NOT NULL,
  PRIMARY KEY (`item_id`),
  UNIQUE INDEX `item_id_UNIQUE` (`item_id` ASC) VISIBLE,
  INDEX `fk_Items_Types1_idx` (`Types_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_Items_Types1`
    FOREIGN KEY (`Types_type_id`)
    REFERENCES `cs340_russda`.`Types` (`type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs340_russda`.`Scenarios_has_Items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs340_russda`.`Scenarios_has_Items` (
  `Scenarios_has_Items_id` INT NOT NULL AUTO_INCREMENT,
  `Scenarios_scenario_id` INT NOT NULL,
  `Items_item_id` INT NOT NULL,
  `quantity` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`Scenarios_has_Items_id`),
  INDEX `fk_Scenarios_has_Items_Items1_idx` (`Items_item_id` ASC) VISIBLE,
  INDEX `fk_Scenarios_has_Items_Scenarios_idx` (`Scenarios_scenario_id` ASC) VISIBLE,
  UNIQUE INDEX `Scenarios_has_Items_id_UNIQUE` (`Scenarios_has_Items_id` ASC) VISIBLE,
  CONSTRAINT `fk_Scenarios_has_Items_Scenarios`
    FOREIGN KEY (`Scenarios_scenario_id`)
    REFERENCES `cs340_russda`.`Scenarios` (`scenario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Scenarios_has_Items_Items1`
    FOREIGN KEY (`Items_item_id`)
    REFERENCES `cs340_russda`.`Items` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs340_russda`.`Dungeons_has_Monsters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs340_russda`.`Dungeons_has_Monsters` (
  `Dungeons_has_Monsters_id` INT NOT NULL AUTO_INCREMENT,
  `Dungeons_dungeon_id` INT NOT NULL,
  `Monsters_monster_id` INT NOT NULL,
  `quantity` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`Dungeons_has_Monsters_id`),
  INDEX `fk_Dungeons_has_Monsters_Monsters1_idx` (`Monsters_monster_id` ASC) VISIBLE,
  INDEX `fk_Dungeons_has_Monsters_Dungeons1_idx` (`Dungeons_dungeon_id` ASC) VISIBLE,
  UNIQUE INDEX `Dungeons_has_Monsters_id_UNIQUE` (`Dungeons_has_Monsters_id` ASC) VISIBLE,
  CONSTRAINT `fk_Dungeons_has_Monsters_Dungeons1`
    FOREIGN KEY (`Dungeons_dungeon_id`)
    REFERENCES `cs340_russda`.`Dungeons` (`dungeon_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dungeons_has_Monsters_Monsters1`
    FOREIGN KEY (`Monsters_monster_id`)
    REFERENCES `cs340_russda`.`Monsters` (`monster_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
